language: ruby
cache: bundler
sudo: false
rvm:
- 2.6.3
before_install:
- gem install -v 2.0.2 bundler
services:
- mongodb
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
env: RACK_ENV=test
