language: ruby
cache: bundler
rvm:
- 2.0.0
script:
- bundle exec rspec
services:
- mongodb
env: RACK_ENV=test
before_install:
- openssl aes-256-cbc -K $encrypted_09633be6cc24_key -iv $encrypted_09633be6cc24_iv
  -in escualo_rsa.enc -out escualo_rsa -d
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo-deploy/master/travis_deploy
  && chmod u+x travis_deploy && ./travis_deploy classroom-api classroom.mumuki.io
