common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: mumuki
  password: mumuki

test:
  <<: *common
  database: mumuki_classroom_test
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: mumuki_classroom_integration
  pool: 5
  timeout: 5000

