common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: mumuki
  password: mumuki

development:
  <<: *common
  database: academia_development
  pool: 5
  timeout: 5000

test:
  <<: *common
  database: mumuki_classroom_test
  pool: 5
  timeout: 5000
