development:
  options:
    raise_not_found_error: false
  clients:
    default:
      database: classroom
      options:
        max_pool_size: 8
        min_pool_size: 1
      hosts:
        - localhost:27017

test:
  options:
    raise_not_found_error: false
  clients:
    default:
      database: classroom_test
      options:
        max_pool_size: 1
      hosts:
        - localhost:27017

production:
  options:
    raise_not_found_error: false
  clients:
    default:
      database: "<%=ENV['MUMUKI_MONGODB_DATABASE']%>"
      options:
        user: "<%=ENV['MUMUKI_MONGODB_USER']%>"
        password: "<%=ENV['MUMUKI_MONGODB_PASSWORD']%>"
        roles:
          - readWrite
        max_pool_size: 8
        min_pool_size: 1
      hosts:
  <%= (ENV['MUMUKI_MONGODB_CONNECTION_STRING'] || '').split(',').map { |it| "        - #{it}\n" }.join %>
