development:
  clients:
    default:
      database: classroom
      hosts:
        - localhost:27017
      options:
        max_pool_size: 8
        min_pool_size: 1
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: classroom_test
      hosts:
        - localhost:27017
      options:
        max_pool_size: 1
  options:
    raise_not_found_error: false
