common: &common
  pool: 8

production:
  <<: *common
  host: <%=ENV['MUMUKI_MONGODB_HOST']%>
  port: <%=ENV['MUMUKI_MONGODB_PORT']%>
  user: <%=ENV['MUMUKI_MONGODB_USERNAME']%>
  password: <%=ENV['MUMUKI_MONGODB_PASSWORD']%>
  database: <%=ENV['MUMUKI_MONGODB_DATABASE']%>

development:
  <<: *common
  host: localhost
  port: 27017
  database: classroom

test:
  <<: *common
  host: <%=ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost'%>
  port: <%=ENV['MONGO_PORT_27017_TCP_PORT'] || 27017%>
  database: classroom_test
