production:
  host: <%=ENV['MUMUKI_MONGODB_HOST']%>
  port: <%=ENV['MUMUKI_MONGODB_PORT']%>
  user: <%=ENV['MUMUKI_MONGODB_USERNAME']%>
  password: <%=ENV['MUMUKI_MONGODB_PASSWORD']%>
  database: <%=ENV['MUMUKI_MONGODB_DATABASE']%>

development:
  host: localhost
  port: 27017
  database: bibliotheca

test:
  host: localhost
  port: 27017
  database: bibliotheca-test
