require_relative './models/concerns/extensions'
require_relative './models/concerns/with_submission_process'

require_relative './models/submission'
require_relative './models/exercise'
require_relative './models/last_assignment'

require_relative './models/organization'
require_relative './models/failed_submission'
require_relative './models/guide_progress'
require_relative './models/assignment'
require_relative './models/follower'
require_relative './models/student'
require_relative './models/teacher'
require_relative './models/course'
require_relative './models/guide'
require_relative './models/exam'
require_relative './models/user'
