require_relative './models/concerns/extensions'

require_relative './models/organization'
require_relative './models/submission'
require_relative './models/exercise'
require_relative './models/assignment'
require_relative './models/follower'
require_relative './models/student'
require_relative './models/course'
require_relative './models/guide'
require_relative './models/exam'
require_relative './models/user'
